### ISSUE TITLE
Incorrect search result

### ISSUE THREAD

**Issue by gpip** [ryanfox/bktree#3]
Hello, I was testing your library and found the following issue:

```
import bktree

def test_search():
    descr1 = 0b101
    descr2 = 0b000

    tree = bktree.Tree()
    tree.add(descr1)
    tree.add(descr2)

    # return both
    assert len(tree.search(descr2, 2)) == 2

    # return itself
    result = tree.search(descr2, 1)
    assert len(result) == 1
    assert result[0].num == descr2

test_search()
```

The asserts fail because that call to tree.search is returning an empty list.

On `bktree/bktree.py` the line 40 causes the above to happen, as `descr2` is added as a child of the root `descr1` and their distance is 2. Isn't it stopping the search too soon?

**Comment by gpip** [comment]
Shouldn't it do something like the following?

```
-            if distance > max_distance:
-                continue
+            if distance <= max_distance:
+                found.append(node)
 
-            found.append(node)
```

**Comment by ryanfox** [comment]
You're right.  I'll take a look at the PRs.
